%% eigenvalues

paramset = load('ParameterSets/cgDNA+ps1_posdef.mat');

% widom
%widomnucleosome = 'CTGGAGAATCCCGGTGCCGAGGCCGCTCAATTGGTCGTAGACAGCTCTAGCACCGCTTAAACGCACGTACGCGCTGTCCCCCGCGTTTTAACCGCCAAGGGGATTACTCCCTAGTCTCCAGGCACGTGTCAGATATATACATCCTGT';

% widom centre 73

%widomnucleosome = 'GTAGACAGCTCTAGCACCGCTTAAACGCACGTACGCGCTGTCCCCCGCGTTTTAACCGCCAAGGGGATTACTC';

%widomnucleosome = 'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA';

widomnucleosome = 'ATATATATATATATATATATATATATATATATATATATATATATATATATATATATATATATATATATATATATATATATATATATATATATATATATATATATATATATATATATATATATATATATATATATATATATATATATA';

widomnucleosome =  [random_dna(147)];


[shapesW, stiffW] = constructSeqParms(widomnucleosome, paramset);


eigW = eig(stiffW);

minW = min(eigW)

maxW = max(eigW)

meanW = mean(eigW)

% figure 
% 
% plot(eigW)
% 
% title('A')